"""Val new-rule generator for bit_manipulation — a thin wrapper over the shared
rule core in reasoners.bit_rule (so the measured val instances and the training
traces are generated by the SAME code and cannot drift).

See reasoners/bit_rule.py for the calibrated rule family (hom/het mixture).
"""

from reasoners.bit_rule import (
    bit_at as _bit,
)
from reasoners.bit_rule import (
    build_rule,
    columns,
    problem_tag,
    rule_family,
    rule_signature,
    sample_problem,
)
from reasoners.bit_rule import (
    eval_column as _eval_column,
)
from reasoners.bit_rule import (
    pack as _pack,
)
from reasoners.store_types import Problem
from val.generators import register

__all__ = [
    "build_rule",
    "columns",
    "generate",
    "problem_tag",
    "rule_family",
    "rule_signature",
    "_bit",
    "_pack",
    "_eval_column",
]


def generate(seed: int, difficulty: int) -> Problem:
    p = sample_problem(seed, difficulty)
    # val ids carry a 'val-' prefix; id[2] (family) is used by tests/breakdowns.
    return Problem(
        id=f"val-{p.id}",
        category=p.category,
        examples=p.examples,
        question=p.question,
        answer=p.answer,
        prompt=p.prompt,
    )


register("bit_manipulation", generate, rule_signature)
