"""Shared rule core for the bit_manipulation new-rule family.

Both the val generator (val/generators/bit_manipulation.py) and the training-trace
emitter (reasoners/bit_trace.py) import this, so the measured val instances and the
trained data are generated by the SAME code and cannot drift. Dependency direction
stays clean: val and reasoners.bit_trace import reasoners.bit_rule; this module
never imports val.

Real bit rules are a MIXTURE of homogeneous and heterogeneous problems (measured on
1,602 train problems): ~43% mix >=2 ops across the 8 output bits, ~48% vary operand
offset by column, the rest are a single op at a global stride. Each problem gets one
`het` coin (~46%). Coarse family mix: ~65% pairwise-2input / ~20% routing / ~15%
complex (>=1 three-input majority/choice column). No affine/xor-mask/arbitrary
truth tables (~0% of real). Answers are correct by construction.
"""

from __future__ import annotations

import random
from collections.abc import Callable

from reasoners.store_types import Example, Problem

HEADER = (
    "In Alice's Wonderland, a secret bit manipulation rule transforms 8-bit "
    "binary numbers. The transformation involves operations like bit shifts, "
    "rotations, XOR, AND, OR, NOT, and possibly majority or choice functions."
)

PAIR_OPS = ("AND", "OR", "XOR", "AND-NOT", "OR-NOT", "XOR-NOT")
HET_PROB = 0.46  # P(heterogeneous); matches ~43% mix-ops / ~48% vary-offset

# A "column rule" is a tuple (kind, *params) for one output bit:
#   ("route", p, neg)   -> in[p]   (xor neg)            (identity routing / NOT)
#   ("pair", op, p, q)  -> op(in[p], in[q])             (2-input boolean)
#   ("maj", p, q, r)    -> majority(in[p],in[q],in[r])
#   ("choice", p, q, r) -> in[q] if in[p] else in[r]


def bit_at(x: int, p: int) -> int:
    return (x >> (7 - p)) & 1


def pack(bits: list[int]) -> int:
    out = 0
    for j in range(8):
        out |= bits[j] << (7 - j)
    return out


def eval_column(col: tuple, x: int) -> int:
    kind = col[0]
    if kind == "route":
        _, p, neg = col
        b = bit_at(x, p)
        return 1 - b if neg else b
    if kind == "pair":
        _, op, p, q = col
        u, v = bit_at(x, p), bit_at(x, q)
        if op.endswith("-NOT"):
            v = 1 - v
        base = op.split("-")[0]
        if base == "AND":
            return u & v
        if base == "OR":
            return u | v
        return u ^ v
    if kind == "maj":
        _, p, q, r = col
        return 1 if (bit_at(x, p) + bit_at(x, q) + bit_at(x, r)) >= 2 else 0
    if kind == "choice":
        _, p, q, r = col
        return bit_at(x, q) if bit_at(x, p) else bit_at(x, r)
    raise ValueError(f"unknown column kind: {kind}")


def _rand_distinct_pair(rng: random.Random) -> tuple[int, int]:
    p = rng.randint(0, 7)
    q = rng.randint(0, 7)
    while q == p:
        q = rng.randint(0, 7)
    return p, q


def _build_columns(rng: random.Random, profile: str, het: bool) -> list[tuple]:
    if profile == "rot":
        glob_neg = rng.random() < 0.3
        if rng.random() < 0.90:  # coherent rotation (the routing bulk)
            k = rng.randint(1, 7)
            return [("route", (j + k) % 8, glob_neg) for j in range(8)]
        perm = list(range(8))  # arbitrary permutation (the rare routing tail)
        rng.shuffle(perm)
        return [("route", perm[j], glob_neg) for j in range(8)]

    # pairwise / complex share a global op + stride used by the HOMOGENEOUS case.
    global_op = rng.choice(PAIR_OPS)
    a = rng.randint(0, 7)
    b = (a + rng.randint(1, 7)) % 8
    c = (a + rng.randint(1, 7)) % 8
    three: set[int] = set()
    if profile == "complex":
        three = set(rng.sample(range(8), rng.randint(1, 3)))

    cols: list[tuple] = []
    for j in range(8):
        if j in three:  # a genuine 3-input column (majority / choice)
            kind = rng.choice(("maj", "choice"))
            if het:
                p, q, r = rng.sample(range(8), 3)
            else:
                p, q, r = (a + j) % 8, (b + j) % 8, (c + j) % 8
            cols.append((kind, p, q, r))
        else:  # a 2-input column
            if het:
                op = rng.choice(PAIR_OPS)
                p, q = _rand_distinct_pair(rng)
            else:
                op, p, q = global_op, (a + j) % 8, (b + j) % 8
            cols.append(("pair", op, p, q))
    return cols


def _col_sig(col: tuple) -> str:
    return ",".join(str(x) for x in col)


def _profile_and_columns(seed: int) -> tuple[str, bool, list[tuple]]:
    rng = random.Random(seed)
    roll = rng.random()
    profile = "pairwise" if roll < 0.65 else ("rot" if roll < 0.85 else "complex")
    het = profile != "rot" and rng.random() < HET_PROB
    return profile, het, _build_columns(rng, profile, het)


def columns(seed: int) -> list[tuple]:
    """The 8 per-output-bit column rules for *seed* (for traces/tests/breakdowns)."""
    return _profile_and_columns(seed)[2]


def problem_tag(seed: int) -> str:
    """Family + homogeneity, e.g. 'pairwise/het' — the stratum for breakdowns."""
    profile, het, _ = _profile_and_columns(seed)
    return f"{profile}/{'het' if het else 'hom'}"


def build_rule(seed: int) -> tuple[str, Callable[[int], int]]:
    """Return (canonical_signature, apply) for the rule selected by *seed*."""
    profile, het, cols = _profile_and_columns(seed)
    signature = f"{profile}:{'het' if het else 'hom'}:" + ";".join(
        _col_sig(c) for c in cols
    )

    def apply(x: int) -> int:
        return pack([eval_column(c, x) for c in cols])

    return signature, apply


def rule_signature(seed: int) -> str:
    return build_rule(seed)[0]


def rule_family(seed: int) -> str:
    """Coarse family label ('pairwise' / 'rot' / 'complex') for breakdowns."""
    return rule_signature(seed).split(":", 1)[0]


def distinct_inputs(seed: int, count: int) -> list[int]:
    if count > 256:
        raise ValueError(f"count={count} exceeds the 8-bit value pool (256)")
    rng = random.Random(seed * 1000 + 1)  # separate stream from the rule
    seen: list[int] = []
    while len(seen) < count:
        v = rng.randint(0, 255)
        if v not in seen:
            seen.append(v)
    return seen


def render_prompt(example_lines: list[str], query_bits: str) -> str:
    return (
        f"{HEADER}\n\nHere are some examples of input -> output:\n"
        + "\n".join(example_lines)
        + f"\n\nNow, determine the output for: {query_bits}"
    )


def sample_problem(seed: int, difficulty: int) -> Problem:
    """A new-rule bit problem; answers correct by construction (shared by val
    generator + training-trace emitter)."""
    signature, apply = build_rule(seed)
    family = signature.split(":", 1)[0]
    values = distinct_inputs(seed, difficulty + 1)
    example_ints, query_int = values[:difficulty], values[difficulty]

    example_lines: list[str] = []
    examples: list[Example] = []
    for x in example_ints:
        x_bits = format(x, "08b")
        y_bits = format(apply(x), "08b")
        example_lines.append(f"{x_bits} -> {y_bits}")
        examples.append(Example(input_value=x_bits, output_value=y_bits))

    query_bits = format(query_int, "08b")
    answer_bits = format(apply(query_int), "08b")
    return Problem(
        id=f"bit_manipulation-{family}-{seed}",
        category="bit_manipulation",
        examples=examples,
        question=query_bits,
        answer=answer_bits,
        prompt=render_prompt(example_lines, query_bits),
    )
